name: Claude Code Quality Check

on:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  checks: write
  id-token: write

jobs:
  code-quality:
    runs-on: ubuntu-latest
    name: Analyze code quality with Claude

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv sync

      - name: Run code quality checks
        run: |
          make check || echo "Quality checks completed with warnings"

      - name: Claude Code Analysis
        uses: anthropics/claude-code-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            Please analyze this pull request focusing on:
            - Code quality and best practices
            - Security vulnerabilities
            - Performance optimizations
            - Documentation improvements

      - name: Post analysis results
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const analysisFile = process.env.CLAUDE_ANALYSIS_FILE || 'claude-analysis.md';

            if (fs.existsSync(analysisFile)) {
              const analysis = fs.readFileSync(analysisFile, 'utf8');

              if (context.payload.pull_request) {
                github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: `## Claude Code Quality Analysis\n\n${analysis}`
                });
              }
            }
